### PR TITLE
Add .nvmrc file, set version to 16.

### PR DESCRIPTION
**Pull request by shadoath**
bundled with pnpm

### CODE REVIEW

**Comment by aruniverse** [comment]
what is the point of this pr?

**Comment by shadoath** [comment]
> what is the point of this pr?

I noticed that the tests on #26 where failing. [Looked](https://app.netlify.com/sites/adblock-detect-react-test/deploys/655de11cd6de8900082e0dea) like it was due to a mismatch of pnpm and node.

In this PR the tests get past the `initialize` phase then fail after.

**Comment by shadoath** [comment]
Now there is a new Error in the Deploy tests:
`Deploy did not succeed: Deploy directory "test-app/dist" does not exist`

**Comment by shadoath** [comment]
Do you still use `Netlify`?

**Comment by aruniverse** [comment]
> Do you still use `Netlify`?

the site still exists, but its not the main one i use anymore 

https://adblock-detect-react-test.netlify.app/

if this is to get the checks to pass to get the other pr through and published, i will force merge it in and ingore the netlify checks

**Pull request closed without merging**
